using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CameraWorking : MonoBehaviour
{
    float xRotateMove;
    float yRotateMove;

    float rotateSpeed = 360f;

    float yRotate;
    float xRotate;

    // Update is called once per frame
    void Update()
    {
        xRotateMove = -Input.GetAxis("Mouse Y") * Time.deltaTime * rotateSpeed;
        yRotateMove = Input.GetAxis("Mouse X") * Time.deltaTime * rotateSpeed;

        yRotate = transform.eulerAngles.y + yRotateMove;
        //xRotate = transform.eulerAngles.x + xRotateMove; 
        xRotate = xRotate + xRotateMove;

        xRotate = Mathf.Clamp(xRotate, -90, 90); // 위, 아래 고정

        transform.eulerAngles = new Vector3(xRotate, yRotate, 0);
    }
}
